batting = read.csv('Batting.csv')
head(batting)
str(batting)
head(batting$AB)
head(batting$X2B)
batting$BA = batting$H / batting$AB
head(batting)
tail(batting$BA)
batting$X1B = batting$H - batting$X2B - batting$X3B-batting$HR
head(batting)
batting$OBP = (batting$H + batting$BB + batting$HBP) / (batting$AB + batting$BB + batting$HBP + batting$SF)
head(batting)
batting$SLG = (batting$X1B + (2 * batting$X2B) + (3 * batting$X3B) + (4 * batting$HR)) / batting$AB
head(batting)
str(batting)
sal = read.csv('Salaries.csv')
summary(batting)
batting = subset(batting, yearID>=1985)
summary(batting)
summary(sal)
combo = merge(batting, sal, by = c('playerID', 'yearID'))
summary(combo)
lost_players = subset(combo, playerID %in% c('giambja01', 'damonjo01', 'saenzol01'))
head(lost_players)
lost_players = subset(lost_players, yearID==2001)
head(lost_players)
lost_players = subset(lost_players, playerID, H, X2B, X3B, HR, OBP, SLG, BA, AB)
lost_players = lost_players[, c('playerID', 'H', 'X2B', 'X3B', 'HR', 'OBP', 'SLG', 'BA', 'AB')]
head(lost_players)
head(combo)
summary(combo)
combo = subset(combo, yearID == 2001)
summary(combo)
library(dplyr)
avail.players = combo
library(ggplot2)
ggplot(avail.players, aes(x=OBP, y = salary)) + geom_point()
avail.players = filter(avail.players, salary<8000000, OBP>0)
avail.players = filter(avail.players, AB>=500)
possible = head(arrange(avail.players, desc(OBP)), 10)
possible = possible[, c()]